<ul id="menu" class="page-sidebar-menu">
    <li >
    <a href="{{ route('admin.index') }}">
            <i class="livicon" data-name="dashboard" data-size="18" data-c="#418BCA" data-hc="#418BCA"
               data-loop="true"></i>
            <span class="title">Dashboard </span>
        </a>
    </li>

    <li >
            <a href="#">
                <i class="livicon" data-name="user" data-size="18" data-c="#6CC66C" data-hc="#6CC66C"
                   data-loop="true"></i>
                <span class="title">Admin Management</span>
                <span class="fa arrow"></span>
            </a>
            <ul class="sub-menu">
                <li>
                <a href="{{ route('admin.admin-management.permissions') }}">
                        <i class="fa fa-angle-double-right"></i>
                        Permissions
                    </a>
                </li>
                <li>
                    <a href="{{ route('admin.roles') }}">
                        <i class="fa fa-angle-double-right"></i>
                        Roles
                    </a>
                </li>
                <li >
                    <a href="{{ route('admin.users') }}">
                        <i class="fa fa-angle-double-right"></i>
                        Admin
                    </a>
                </li>
            </ul>
     </li>
     <li>
        <a href="{{ route('admin.members') }}">
            <i class="livicon" data-name="users" data-size="18" data-c="#1DA1F2" data-hc="#1DA1F2"
               data-loop="true"></i>
            Member
        </a>
    </li>
    <li>
        <a href="">
            <i class="livicon" data-name="share" data-size="18" data-c="#F89A14" data-hc="#F89A14"
>>>>>>> master
               data-loop="true"></i>
            Tree
        </a>
    </li>
    <li >
        <a href="#">
            <i class="livicon" data-name="medal" data-size="18" data-c="#6CC66C" data-hc="#6CC66C"
               data-loop="true"></i>
            <span class="title">Training</span>
            <span class="fa arrow"></span>
        </a>
        <ul class="sub-menu">
            <li>
                <a href="">
                    <i class="fa fa-angle-double-right"></i>
                    Training Management
                </a>
            </li>
            <li>
                <a href="">
                    <i class="fa fa-angle-double-right"></i>
                    Training Class
                </a>
            </li>
        </ul>
    </li>
    <!-- Menus generated by CRUD generator -->
    @include('admin/layouts/menu')
</ul>